### ISSUE TITLE
v2.2.0-RC Check List

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#117]
@AnssiR66, the Mid-November ETA is approaching fast! We need to wrap up the current work and focus on the StdLib `v2.2.0-RC` release. Here's how we should proceed:

- [x] **Finish all work on branch `dev-2.2.0`**:
    + [x] Complete all the pending tasks that can be dealt with before the ETA.
    + [x] __Polish all StdLib sources__ — fix indentation, headings styles, delete/update obsolete doc comments, document new features:
        * [x] `lib_actors.i`.
        * [x] `lib_classes.i`.
        * [x] `lib_clothing.i`.
        * [x] `lib_definitions.i`.
        * [x] `lib_liquid.i`.
        * [x] `lib_locations.i`.
        * [x] `lib_messages_library.i`.
        * [x] `lib_messages_runtime.i`.
        * [x] `lib_verbs.i`.
        * [x] `lib_verbs_restrictions.i`.
    + [x] Polish shipped examples (even if the _StdLib Manual_ won't be included in the package, we could include the examples):
        * [x] Polish sources and comments.
        * [x] Remove from comments references to chapters and sections (most of them are broken due to re-organization of the Manual, and in this case we won't be providing the Manual, so they're useless).
    + [x] Finish updating the CHANGELOG.
    + [x] Create a new dedicated README file for `v2.0.0-RC` (locally), in AsciiDoc (or pandoc markdown), so that we can include a README in HTML in the distribution package.
- [x] **Create a temporary [`v2.2.0-RC` branch][v2.2.0-RC branch]**, for the pre-release tweaks:
    + [x] Replaces with `v2.2.0-RC` any references to StdLib `v2.2.0` or `v2.2.0-WIP` in:
        * [x] StdLib sources.
        * [x] Example files.
        * [x] CHANGELOG.
        * [x] READMEs due for package inclusion.
        * [x] Any file or doc that is due for package inclusion.
    + [x] Adapt the contents of various documents, as required for this special pre-release:
        * [x] CHANGELOG.
        * [x] READMEs (packaged).
        * [x] Other docs or files that will be included.
- [x] **Prepare ZIP package** — when all file editing is done, we'll create a ZIP file to distribute when the ETA arrives:
    + [x] **Convert EOLs to `LF`** — all ALAN sources need to be run through `dos2unix`, so that they'll have `LF` line endings. We can't keep `CRLF` EOLs because they'd create problems for Linux and Mac users.
    + [x] **Create ZIP Archive** — Prepare locally the distribution files and create a ZIP archive (use standard compression algorithms only).
    + [x] **Store Package somewhere** — we could host the v2.2.0-RC Package on Google Drive, by creating a dedicated read-only folder. The link doesn't need to be kept alive for long, it could actually be terminated when `v2.2.0` is finally released:
      - https://drive.google.com/drive/folders/1BP4OM3wKvZP1zsVs4aEZpVlR8LKdR137
    + [ ] **Announce the Pre-Release** — we need to send an announcement presenting `v2.2.0-RC` and its features, and provide the download link, etc.:
        * [x] Alan-IF list on Yahoo.
        * [ ] [rec.arts.int-fiction](https://groups.google.com/g/rec.arts.int-fiction/about)
        * [ ] Others?

[v2.2.0-RC branch]: https://github.com/AnssiR66/AlanStdLib/tree/v2.2.0-RC "View branch"

**Comment by tajmone** [comment]
# Highest Priority: StdLib Sources

Right now, we should focus on polishing the library sources, for they will be the main source of reference on how to use the various library features, since there's no way the _StdLib Manual_ could be finished in two weeks. We need to:

- [x] Ensure that all the in-comments documentation matches the current library:
    + [x] Fix or remove obsolete statements or examples referring to previous versions of the library.
    + [x] Add missing documentation and code examples, where needed.
    + [x] Polish the sources to make them easy to read.

# Annotating the StdLib Manual

Since we'll be advising end users to check the online HTML Preview of the _StdLib Manual_ from the `dev-2.2.0` branch (which will always provide the latest version of the Manual, until `v2.0.0` is released), we should add admonition blocks at the beginning of Parts, Chapters and Sections (Level 2) mentioning their current status in relation to `v2.0.0`.

I've already started to add some of these admonitions, adding a brief description of the contents status, task lists for what still need to be done, and (where applicable) links to the repository Issues discussing the various features updates that need to be integrated in the _Manual_.

These admonition blocks should be a guidance for both end users (who need to known how reliable the contents are) as well as for us (who need to plan the contents updates).

Before the ETA arrives, at least every Part should have an admonition block informing the reader about its contents status. Any Part, Chapter or Section which was already updated to `v2.0.0`, should have an admonition block stating it clearly, so that end users can safely rely on its contents.

# Manual Updates

@AnssiR66, if you have finished writing any of the texts discussed in #104, please send them before the 10th of November, because the last days before the ETA release will be rather busy — also, after the package release I'll be taking a break until mid- or end-January, since I want to focus on creating an adventure during the season holidays, and have also piled up a lot of work which I'll need to catch up with.

**Comment by tajmone** [comment]
# Planning to Release Over Weekend

@AnssiR66, if it's OK with you, I'd like to finish all the pending polishing tasks and the start working locally on the RC distribution package — add the examples from the _StdLib Manual_, the _Clothing Guide_ tutorial, and create an _ad hoc_ `README.html` to include in the package.

Once the package is ready, I'll send it to you via email, so you can preview it; once you approve it, I was thinking of hosting it on my Google Drive space, creating a dedicated read-only folder that is publicly accessible to anyone — that's just because it's already setup for use; but if you have better alternatives in mind it's fine.

Then I'll write the draft of the presentation email, and sent it to you so you might further edit it — I'll be summarizing the new features, and the nature of the RC pre-relase, but since it's going to be an email from both of us, you should edit it and add whatever text you think is required.

My hope is to be able to finish all pending chores during the weekend, and announce the new package on Sunday night — or by Monday morning, in case of delays.

Now that we've discovered that the ALAN Yahoo list is shutting down on Dec. 15, I think we should release the package as soon as we can, in case communications are interrupted on the list before community members have a chance to download the package and ask us questions. I was hoping to count on the newsgroup to provide support during the holidays, since the _Manual_ isn't yet complete, but this might not be the case if setting up the new list will take long, which might result in a gap-period in which the ALAN IF list is not available.

What do you think?

**Comment by AnssiR66** [comment]
Yes, this sounds good. Do send me the e-mail briefing when it is ready, and I will read through it (and add something if needed). Do you wish me to write something to chapter 3 of the manual (library overview), or other places?
-Anssi


________________________________

**Comment by tajmone** [comment]
OK, I should be able to send you the preview by Sunday lunch.

> Do you wish me to write something to chapter 3 of the manual (library overview), or other places?

Please, go ahead. I might not be resuming work on the repository until mid-January, after the RC release; but anything you send me I'll save it locally (and if I find a few free time slots I'll add it to the ADoc sources).
