### ISSUE TITLE
Shoot Verb Lack CHECKs for FIREABLE

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#125]
In `lib_verbs.i`, the `shoot_with` verb definition lack CHECKs to verify that the weapon `IS fireable` — syntax `shoot (target) 'with' (weapon)`.

Although the verb doesn't actually do much, beside saying that the action is inappropriate, if authors do override the verb on custom weapons instances (or subclasses), shouldn't the main verb should CHECK that the weapon of the parameter is indeed `fireable`?

Or was this left out _because_ the verb needs to be overridden anyhow?

IMO, if the player attempts to 'shoot Boo with baseball bat', the action should fail because baseball bats are not fireable weapons, and not because by default the library prevents any aggressive actions.

**Comment by AnssiR66** [comment]
Yes, you're right. There should be a check for being fireable, for the shoot_with verb. The message can be just the basic "That's not something you can $v." (check_verb_suitable), I guess.
