### ISSUE TITLE
Question about `present_actor` attribute

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#14]
Ciao Anssi,

I've noticed that the `present_actor` attribute (on every `ACTOR`) is defined but not actually used anywhere (it doesn't occur anywhere else in the library except at its definition).

I wanted to ask you:

- what is its intended use?
- is it created for potential uses by the authors? (even if the StdLib doesn't use it)
- was it meant for internal library use?
- was it added for some feature not yet implemented?
- or is just a left over attribute from older versions of the library?

I wanted to understand if I should translate it to Italian, or even remove it altogether from the library.

If it's intended for potential uses by authors, I might as well remove it — after all, an author can easily add by himself a simple attribute like this one.

**Comment by AnssiR66** [comment]
HI Tristano!

Good that you spotted that, it is a leftover of some experimentation that I did previously, but it is indeed not needed in any way. So, you can skip it in your translation. I will delete it from the file.


Thanks,

-Anssi


________________________________

**Comment by tajmone** [comment]
I've deleted it in commit 18669f9.

Shall we close this issue?
