### ISSUE TITLE
Redundant HEADER Code on PERSON

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#15]
While translating to Italian "`lib_classes.i`" I noticed that the `HEADER` and `EXTRACT` code is duplicated on both `ACTOR` and `PERSON` classes. Except for the code part on `ACTOR` that handles the `hero` (which is not found on `PERSON`), the code produces the same identical messages. (code reproduced at the end of this post)

At the beginning I couldn't understand why after translating to Italian the code on `ACTOR` I was still getting English responses when examining actors. Then I realized that the code is replicated on `PERSON` too, so the responses I was getting where from the latter.

I was wondering if the code on `PERSON` could be safely removed, after all it inherits the same checks and messages from `ACTOR`.

So, I wanted to ask you if there is a specific reason for this duplicate effort — eg, to ensure that the library defined class `PERSON` (and therefore, `MALE` and `FEMALE`) will always behave as intended, even if the author tweaks the `ACTOR` class. Personally, I think that the chances of an author customizing the  `HEADER` and `EXTRACT` behavior and messages on `ACTOR` are quite small — probably, if a customized version is required he/she will implement it on a new custom class (eg, for animals or fantastic creatures, which might require listing their belongings in a different way).

If the duplicated code on `PERSON` is not strictly necessary, I'd rather drop it in favour of inheriting it from `ACTOR`, as its presence might make tracking problems more difficoult when end users want to customize the library, and also require keeping their messages updated in two places.

What do you think about this? Is is safe to remove it or are there reasons to keep it?

### Small Optimization

Also, I think that the following code (present in both classes, and maybe elsewhere in relation to ACTORs):

```alan
IF THIS IS NOT named
THEN SAY THE THIS.
ELSE SAY THIS.
END IF.
```

... could be safely changed to:

```alan
SAY THE THIS.
```

... as all `named` ACTORs will always have been initialiazed by the library to have an empty string in `DETERMINATE`/`INDETERMINATE ARTICLE`; so including `THE` in the `SAY` statement should safely produce nothing with named actors.

## ACTOR HEADER CODE

"`lib_classes.i`" (lines [2059-2100]):

```alan
    CONTAINER
    -- so that actors can receive and carry objects
    HEADER
      IF THIS = hero
        THEN "You are carrying"
        ELSE

          IF THIS IS NOT named
            THEN SAY THE THIS.
            ELSE SAY THIS.
          END IF.

          IF THIS IS NOT plural
            THEN "is carrying"
            ELSE "are carrying"
          END IF.
      END IF.
    ELSE
      IF THIS = hero
        THEN "You are empty-handed."
        ELSE
          IF THIS IS NOT named
            THEN SAY THE THIS.
            ELSE SAY THIS.
          END IF.

          IF THIS IS NOT plural
            THEN "is not carrying anything."
            ELSE "are not carrying anything."
          END IF.

      END IF.

    EXTRACT
      CHECK THIS IS compliant
        ELSE
          "That seems to belong to"
          IF THIS IS NOT named
            THEN SAY THE THIS.
            ELSE SAY THIS.
          END IF.
          "."
```

## PERSON HEADER CODE

"`lib_classes.i`" (lines [2190-2221]):

```alan
EVERY person ISA ACTOR
      CAN talk.

  CONTAINER
    HEADER
      SAY THE THIS.
      IF THIS IS NOT plural
        THEN "is carrying"
        ELSE "are carrying"
      END IF.
    ELSE

      IF THIS IS NOT named
        THEN SAY THE THIS.
        ELSE SAY THIS.
      END IF.

      IF THIS IS NOT plural
        THEN "is empty-handed."
        ELSE "are empty-handed."
      END IF.

    EXTRACT
      CHECK THIS IS compliant
        ELSE "That seems to belong to"
          IF THIS IS NOT named
            THEN SAY THE THIS.
            ELSE SAY THIS.
          END IF.
          "."

END EVERY.
```

[2059-2100]: https://github.com/AnssiR66/AlanStdLib/blob/a852302/lib_classes.i#L2060
[2190-2221]: https://github.com/AnssiR66/AlanStdLib/blob/a852302/lib_classes.i#L2190

**Comment by AnssiR66** [comment]
Hi Tristano,

yes, this is indeed redundant and the code can be scrapped from where it appears under "PERSON". This is another example where I have been blind to my own coding,  and not many other people have gone through the library code to check and test it - probably you are the first one to do it since the release of the v2.x. So, it's very good that you are doing the translation and at the same time checking how things work.

I will remove the unnecessary code. Thanks for notifying me about it!

-Anssi


________________________________

**Comment by tajmone** [comment]
Thanks to you Anssi! You've done an amazing job with the StdLib, and my learning really a lot about IF in general by studying its code.

And I'm glad I can help, I know too well how hard is to maintain a huge codebase like this in time and across major version updates, and how easy it's to get entangled in one's one code. Besides, tracking changes is such a big library it's not an easy task at all.

I've created some automated command scripts to produce all the various library messages in file logs, so after I tweak the library I can easily see how the output text changes by looking at the diffs of the log files that Git reports as being changed. This often helps me to spot unexpected changes in the library messages, that resulted from tweaking the code in one area that also affected other areas.

I should adapt those scripts to English and the English library and add them here, either in the `extras` folder or in a dedicated `test` folder. Then, running a single batch script would update all the test adventures and files.

**Comment by tajmone** [comment]
I hand't noticed the subtle difference, but I was already working/thinking in terms of the Italian message in this case.

I had considered the animal usage case, but imagined that an author would create a special class for that.

As for the Italian library, I've translated both classes' message the same as the Italian language doesn't overlap the English in this case. I have dropped "empty handed" as this in Italian has some shades of meaning which might capture more attention from the player than it's due (usually the sentence implies failure in a task, being defraud, or a guest showing up with no gift for his host; this is due to the phrase being overused in proverbs and common sayings).

Thanks for the clarification, it's worth adding a note about this in the comments of the Italian source, for the benefit of end users who might wish to tweak it or create a new class.

My only last suggestion is to remove the IF blocks that check if ACTOR is named, as simply using `SAY THE THIS` is bullet proof, since the library will always set ARTICLE to null string for named actors — just for the benefit of those studying the library code, more than anything else really.

**Comment by AnssiR66** [comment]
Hi Tristano!
Sorry I forgot to reply to this sooner.



>>My only last suggestion is to remove the IF blocks that check if ACTOR is named, as simply using SAY THE THIS is bullet proof, since the library will always set ARTICLE to null string for named actors — just for the benefit of those studying the library code, more than anything else really.


I agree with this and will make the change. There's indeed some redundancy in how it is formulated now.


Best,

Anssi
