### ISSUE TITLE
Collaborative Effort Proposal

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#20]
Ciao Anssi,

finally I've dealt with some piled up work and can get back to work on the StdLib and its translation.

Since I'd really like to contribute to the StdLib, I wanted to ask you if you could invite me as collaborator to the project. This would allow me to use GitHub's projects and milestones to plan and coordinate the work with you on the long term.

- [Collaborator access on a repository owned by a user account]

While you could (and should) protect the `master` branch from both accidental force pulls that could delete material, you should also be able to restrict any merges to it by setting it to require your review and approval for all pull requests, even from collaborators.

- [About protected branches]

But as a collaborator I could work on branches and contribute to active development on a per features basis (for example, implementing the test suite that I've started to work on).

GitHub's projects dashboards, milestones and issues are really great tools to annotate, discuss, track and implement new features, ideas and bug fixes. Most of this functionality is lost in a closed work model based on fork and pull request, as it only really leaves issues as a interaction tool.

I find myself working on multiple project at once very often, and some times I can't attend for a while due to other tasks demanding my attention, so the projects' tools are a good way to keep track of where I left the work, without having to annotate everything locally. Collaboratively, these tools enhance the whole process as they automatically keep tracks of pull requests, merges and reviews which close issues and milestones, etc.; so the dashboard offer an always up to date snapshot of how the project is evolving.

So, if its OK with you to have me on board, I'd be happy to join the project and help, without interfering with the master branch, and always seeking your blessing before introducing new changes.

[Collaborator access on a repository owned by a user account]: https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account

[About protected branches]: https://help.github.com/articles/about-protected-branches/

**Comment by AnssiR66** [comment]
Hi Tristano,

sorry for the delay in replying. Sure, I will invite you as a collaborator to the StdLib GitHub. In a moment it should work. If there is any problem, I will be in touch.

Best regards!

Anssi




________________________________

**Comment by tajmone** [comment]
Thanks a lot, invitation accepted!

> sorry for the delay in replying

no problem at all, I know you've been busy with work.

I've been overwhelmed by lots of errands in these days too, so I might need a day or two to settle before I can start organize the dashboard. 

Right now, I'm working on making the Italian StdLib self-documenting by using Doxter, a custom docs generator tool I'm developing for the purpose:

- https://tajmone.github.io/doxter/

Hopefully, by tomorrow I shall commit the first version of the self-documenting verbs library module. I'm almost there, just cleaning up the sources and scripts to update the docs. This is going to be quite cool, as now I won't need to update separate markdown documents to track the list of translated verbs and TODOs list — the new system will extract an AsciiDoc file from every Alan source, and then convert them to HTML docs.

But the really cool part is that in the source files the AsciiDoc comments are non intrusive at all, and human readable. For example, with a few small tweak the commented Verbs table is now converted into a real AsciiDoc table, so it looks greate both in the source and in the output HTML document.

Doxter allows to specify the order in which commented regions should be reordered in the final doc, which allows to keep doc-comments in the source file next to where they  naturally belong, and yet be presented in the final document in whichever order is bests for a structured reading.

Ultimately, every library module will have its own documentation file, and then there'll a User Guide that covers the library in more detail, starting from the basics onward, and providing examples. Since the Guide will selectively include parts of the modules' AsciiDoc generated files, its contents will auto-update whenever the source files change. And for the examples, the Guide will be including real example files of the repository into the document flow.

So, hopefully I won't have to worry ever again about documents being out of synch with the library source files.

Of course, as I'm starting to use Doxter for the first time in this real case scenario, I'm discovering new needs as a I go along, and adding new features to it accordingly. Ultimately, when a good balance of features is achieved in the Italian documentation, we could think of applying the same system to the upstream StdLib too, if you like how Doxter worked with the Italian library.

**Comment by tajmone** [comment]
Ciao @AnssiR66,

here's a quick preview of [Doxter] integration into the Italian library.

Currently only the verbs module `lib_verbi.i` has been updated to produce documentation with the new system: 

- [`lib_verbi.i`][lib_verbi.i]

Here is the AsciiDoc file produced by [Doxter], which looks great in GitHub WebUI preview:

- [`lib_verbi.asciidoc`][lib_verbi.asciidoc]


And here is the HTML live preview of the final HTML doc created via Asiidoctor:

- [`lib_verbi.asciidoc`][lib_verbi.asciidoc]


Notice how the original verb tables in the comments have been turned into AsciiDoc tables by very small tweaks (almost unnoticeable):

```
-->tabella_comandi_partita(2100)
--| .Elenco Comandi di Partita
--| [cols="20m,30d,25d,4*^5d",options="header"]
--| |=============================================================================================================
--| | VERBO              | SINONIMI                     | SINTASSI                         |  M  | A |  O  |  B
--~ +--------------------+------------------------------+----------------------------------+-----+---+-----+-----+
--| | abbandona_partita  | quit, Q                      | abbandona [partita]              | {X} | 0 |     |
--| | carica_partita     | restore                      | carica [partita]                 | {X} | 0 |     |
--| | ricomincia_partita | restart                      | ricomincia [partita]             | {X} | 0 |     |
--| | salva_partita      | save                         | salva [partita]                  | {X} | 0 |     |
--| |=============================================================================================================
--<
```

Also the Doxter header and its metadata at the beginning of every source file still look quite natural and intuitive:

```
--= Alan StdLib Italian: Verbi
--| Tristano Ajmone <tajmone@gmail.com>
--~-----------------------------------------------------------------------------
--~ "lib_verbi.i"
--| v0.6.0-Alpha, 2018-10-12: Alan 3.0beta6
--|=============================================================================
--| Adattamento italiano del modulo `lib_verbs.i` della
--| _ALAN Standard Library_ v2.1, (C) Anssi Räisänen, Artistic License 2.1.
--| Ad opera di Tristano Ajmone,  (C) 2018, Artistic License 2.1.
--|=============================================================================

```

... except for the presence of a few special characters (`=`, `|`, `~`) they look by all means standard Alan comments, and preserve the natural look and feel of the source file. Yet, these symbols tell Doxter how to build the Header for this document. 

I've also managed to make it so that from the original table of English verbs only the untraslated verbs are shown in the final Documentation:

```

--| .Elenco dei Verbi Non Tradotti
--| [cols="20m,30d,25d,2*^5d",options="header"]
--| |=======================================================================================================
--| | VERBO              | SINONIMI                           | SINTASSI                          | A |  O  
--~ +--------------------+------------------------------------+-----------------------------------+---+-----
--| | about              | help, info                         | about                             | 0 |
--~*| again              | G                                  | again                             | 0 |
```

... where the lines starting with `--~*` will not be included in the generated table (a tilda after the comment delimiter tells Doxter to ignore that line). This saves me a lot of work since it produces automatically an always up to date table with the list of untranslated verbs (a TODO list of sorts), but at the same time allows me to preserve the original list of English verbs in the source, as a reference.




[Doxter]: https://git.io/doxter "Visit Doxter website"


[lib_verbi.i]: https://github.com/tajmone/Alan3-Italian/blob/master/alanlib_ita/lib_verbi.i
[lib_verbi.asciidoc]: https://github.com/tajmone/Alan3-Italian/blob/master/alanlib_ita/lib_verbi.asciidoc
[lib_verbi.html]: http://htmlpreview.github.io/?https://github.com/tajmone/Alan3-Italian/blob/master/alanlib_ita/lib_verbi.html
