### ISSUE TITLE
Italian Library: Advise on Moving Verb Responses to Lib Messages

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#25]
@AnssiR66, in the Italian library I was thinking of moving all the library messages and verb responses attributes from the `lib_definitions.i` module to the `lib_messages.i` module.

The reasons for this are:

1. The Italian definitions modules is growing quite huge in size, because Italian is more verbose than English, and the grammatical differences are introducing more messages too. Editing the code is beoming tedious due to the file length.
2. The messages module, on the other hand, is the shortest of all, as it contains only the run-time messages overrides.
3. Library messages probably would find a better resonance in the messages module, next to the run-time definitions; after all having all messages in one place is going to make life easier for anyone wishing to customize the library.
4. Since I'm now using Doxter to extract documentation from the source files, having all messages/responses in the same file would also make the output documentation somewhat more intuitive.

The whole operation shouldn't be problematic, I think. I'll only need to `ADD TO` the `definition_block` the attributes which I'm shifting over the other module.

What do you think about this? 

First of all, this is a change moving away from the original library, so I wanted to know if you approve it and if I've your blessing on this. (I'm already keeping notes on such changes in the documentation, since it's a derivative work)

Second, I wanted to ask you if you forsee potential problems in this, or if you think it might be a disruptive change for whatever reason.

Thanks

**Comment by AnssiR66** [comment]
OK, can you just quickly clarify first what you mean by the verb response attributes and library messages in definitions.i - you mean the illegal parameter messages and check responses, right? And all the other "player-customizable" attributes? So, you mean that what would be left in definitions.i would be some default attributes and then the restricted actions coding, the synonyms, and the banner? It's ok if you think it helps the player, and it would be logical as to the naming of the files - messages.i would have all customizable messages, and definitions.i would just have some default definitions. You can do this to the Italian library, but I would at this point keep the English library as it is. I will experiment, though, and let you know how I feel about it :)

**Comment by tajmone** [comment]
>  you mean the illegal parameter messages and check responses, right? 

Exactly, all the string attributes used in the various `SAY` statements around the library (mainly, in `lib_verbs.i` and `lib_classes.i`) — i.e. "library output".

> So, you mean that what would be left in definitions.i would be some default attributes and then the restricted actions coding, the synonyms, and the banner?

Yes, plus the Italian specific parts that deal with gender and other grammar attributes and initializations (which adds considerable length to the original source).

>  It's ok if you think it helps the player,

It should. Currently the library offers the optinal file `mygame_import.i` to provide an easy way for the player to see and edit all the verb responses strings (plus the banner). Moving the string attributes to `lib_messages.i` will achieve a similar result, making `mygame_import.i` redundant.

But right now it's going to make _my_ coding life much easier, because when I work on editing verbs I often have to jump from verb restrictions attributes to response strings, and having the two in separate files would allow me to always have in my editor the verb body in one tab, its correlated response messages in another, and the restrictions attribute in a third tab, so I can easily double check everything that pertains a verb without having to jump up and down the source files.

> but I would at this point keep the English library as it is.

Sure. Probably the English library doesn't suffer from the same problems as the Italian translation, which keeps growing in size (added grammar code, and more response strings than English). In Italian the whole responses system had to be changed beacuse `$v` can't be used as a replacement of the infinitive (e.g. `you can't $v` wouldn't work in Italian because we'd need the infinitive form here).

But I also think that it might ultimately be a good idea, after all the existence of `mygame_import.i` indicates that the response string attributes are the part of the library that end users are most likely going to customize (or at least, consult frequently).

> it would be logical as to the naming of the files — `messages.i` would have all customizable messages, and `definitions.i` would just have some default definitions. 

Indeed, and it would also balance the source files lenght.

**Comment by tajmone** [comment]
Ciao @AnssiR66,

I've managed to successfully move all the messages string attributes over to `lib_messaggi.i` — it all went smooth, not trouble at all. (See commit  [84474f4](https://github.com/tajmone/Alan3-Italian/commit/84474f457c40e334e5243c97dd5458d2bb0e992e))

Here's a comparison of the two modules size in line numbers, before and after this change:

|              | `lib_definizioni.i` | `lib_messaggi.i` |
|--------------|---------------------|------------------|
| lines before |                2163 |              254 |
| lines after  |                1448 |             1002 |

As you can see, it brings back some balance in the modules, and now the two files are both around 1000 lines each.

Having trimmed down 800 lines from `lib_definizioni.i` is going to improve all sort of files operations (diffing, editing, etc.). I'm quite happy with the result.

**Comment by AnssiR66** [comment]
Yes, sounds good! That certainly was a clever idea. I will consider it for the English version at some point...
