### ISSUE TITLE
Help w/ Verbs Meaning for Translation

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#30]
Ciao @AnssiR66,

There are some verbs which I'm not sure how to translate because in Italian they could be translated in different ways, so I wanted to ask you about the original intention behind them.

## Scratch

Which of the following uses should the verb `scratch` cover:

1. scratching as in "scratching one's back/skin" — Italian: _gratta_
2. scratching surfaces (e.g. "scratch the paint") — Italian: _graffia_

I understand that this type of verb is more of a "template" that is up to the user to implement, but in Italian the two verbs mentioned above are quite different and implementing both syntaxes might lead to odd usages — _gratta_ could be used to say "scratch the cat", but _graffia_ used on the cat would sound odd (and terrible too).

## Pry & Pry With

Do `pry` and `pry_with` both refer to:

- Prying as "opening by levering" (e.g. "pry the trunk with crowbar")

Or does `pry` refer to:

- Prying as in "snoop", "inquire", "spy".

**Comment by AnssiR66** [comment]
Hi Tristano!


The verb 'scratch' can refer to both cases in English, so maybe you should just implement two separate verbs for it...?

On the other hand, this action is rarely doing anything useful, so you can just pick one of the translations. And if the player feels he needs the other verb, he can implement it by himself. (or can the other meaning (scratch a cat, in an affectionate sense) be made a synonym of 'rub'?) I think you can go ahead as you deem best...


Pry: I mean prying with a crowbar, not snooping or spying...


Best,

Anssi


________________________________

**Comment by tajmone** [comment]
> The verb 'scratch' can refer to both cases in English, so maybe you should just implement two separate verbs for it...?

Probably yes, mainly because of the verb responses (You can't scratch, etc.), although in this case I could actually use `$v` in the response because for both verbs the infinitive can be made by adding `re` to `$v`:

| imperative | inifinitive |        `$v`       |
|------------|-------------|-------------------|
| graffia    | graffiare   | `$vre`: graffiare |
| gratta     | grattare    | `$vre`: grattare  |

So, the player will see the infinitive of the verb he actually uses.

The problem with this approach is that if the author adds an new alternative syntax with a verb that doesn't form the infinitive that way, then the response would produce gibberish. 

This is a general problem I have to consider with Italian verbs, although in this case it might not be a real issue. Some common verbs don't follow that inifintive pattern:

| (English) | imperative | inifinitive |            `$v`            |
|-----------|------------|-------------|----------------------------|
| _be_      | sii        | essere      | `$vre`: siire (_BAD_!)     |
| _sit_     | siediti    | sedere      | `$vre`: sieditere (_BAD_!) |
| _sit_     | siedi      | sedere      | `$vre`: siedire (_BAD_!)   |
| _take_    | prendi     | prendere    | `$vre`: prendiere (_BAD_!) |
| _take_    | raccogli   | raccogliere | `$vre`: raccogliere (OK!)  |

So, Italian is less flexible here and (unlike with the English Libary) I often have to impose a fix verb in the responses, regardless of how many alternative verbs are available. Obviously, it's nicer when the response show the same verb that the player typed.

> or can the other meaning (scratch a cat, in an affectionate sense) be made a synonym of 'rub'?

That's a good idea. But "rub" is another verb which is going to be problematic to translate. Ultimately, some verbs will end up being translated by multiple separate verbs, and some cases multiple English verbs will end up being translated with a single Italian verb, due to linguistic differences.

E.g. "light", "turn on" and "switch on" are a single verb in Italian: "accendi" (for both light, fires, candles, devices, etc).

Thanks!

**Comment by tajmone** [comment]
# Shoot & Fire

Ciao @AnssiR66, I'm having trouble figuring out how to translate the verbs of the `shoot*` and `fire*` group.

If I've understood correctly, `fire*` is supposed to handle firearms (guns, pistols, rifles, cannons, etc.) which need to have the `fireable` attribute.

I noticed that `shoot*` doesn't carry out checks for the `fireable` attribute, so my guess is that this is a more generic version intended to cover also "white weapons" like bows, crossbows, etc — i.e. weapons that shoot projectiles but don't rely on propellants like gunpowder?

I can't find in Italian distinct verbs for these different cases, as usually we'd use the same verb for all, so I'm trying to figure out if I should just merge these verbs into a unified syntax. But then there is the problem of the checks for `IS fireable`.

Could you please expand a bit on these verbs, and particularly:

- Is `shoot_with` supposed to work with both `firable` and `NOT firable` weapons?
- Is `fireable` intended to be for gun-powedered weapons only? (ie. guns, cannons, etc.)

# Play and Play With

I need to ask you about `play (obj)` and `play with (obj)`.

Are these both intended as in "playing a game" or do they also cover "playing music/instruments"?

Would `play_with` also cover cases like "play with John"?

Would `play` also cover cases like "play the guitar"?

**Comment by AnssiR66** [comment]
Hi Tristano!
Yes, *fire* should only apply to fireable weapons ( = firearms).
*Shoot_with* should apply to both fireable and not fireable weapons.
I recognize that this could bring a problem. If you feel like it, you can scrap *fire* from the Italian library and just use *shoot*. And just omit the check of a weapon being fireable. Would this solve the problem?

*Play* can basically apply to both instruments and games.  Now that you ask, I am actually not 100% why I saw it necessary to introduce 'play_with' to the library. "Play with John" should be possible, for example when challenging an NPC to a game of cards, chess or something else. However, other verbs (coined by the author) could be better, such as 'play against' or 'challenge'. With objects, I am not sure of the actual practical usage of this verb.

-Anssi


________________________________

**Comment by tajmone** [comment]
Thanks a lot Anssi, these answers have helped. I'm finishing translating the last verbs of the library (I should finish them all this week). Of course, they still need lot's of work in translating the responses, creating alternative syntaxes or synonyms, etc — but at least once the basic verbs and syntaxes are in place I can start actually using the library for a real adventure.

> `Shoot_with` should apply to both fireable and not fireable weapons.
I recognize that this could bring a problem.

I'll have to dig into it, but I can't think of a specific verb for non firearms in Italian. Weapons either use the same verb as "shooting" a firearm, or they use special verbs that are only for that weapon (eg. a bow, a catapult, etc.). So it's either a verb that covers all weapons that expell a projectile, or it has to be a specialized verb which the author will have to implement by himself according to need.

I'm sure I'll come up with something...

> `Play` can basically apply to both instruments and games.

Thanks! Then I'll probably either chose one of the two or add an extra verb to cover both here.
