### ISSUE TITLE
Brief Verb Not Working

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#32]
- [x] **StdLib Sources** — remove `brief` and `verbose` and all references to them:
    + [x] `lib_definitions.i`:
        * `CAN 'brief'`/`verbose`
        * `MAKE my_game 'brief'`/`verbose`
    + [x] `lib_verbs.i`:
        * Verbs Table
        * `SYNTAX brief`/`verbose`
        * `META VERB brief`/`verbose`
- [x] **Test Suite** — remove any tests on `brief` and `verbose`:
    + [x] `tests/misc/meta-verbs.a3sol`
- [x] **StdLib Manual** — remove `brief` and `verbose` and all references to them:
    + [x] Manual contents and examples.
    + [x] `table_verbs.dsv` (Verbs Table, CSV source)
- [x] **Extras** — remove `brief` and `verbose` and all references to them:
    + [x] `mygame_import.i`
    + [x] `readme.txt`

-------------------------------------------------------------------------------

Ciao Annsi,

I've tested commenting out the `Entered` part in `lib_locations.i`:

```alan
ADD TO EVERY LOCATION
  HAS visited 0.
  HAS described 0.

--  ENTERED
--     IF CURRENT ACTOR = hero
--      THEN
--        INCREASE visited OF THIS.
--        INCREASE described OF THIS.
--        -- The "described" attribute increases also after LOOK (see 'verbs.i').
--     END IF.

END ADD TO.
```

and, as we suspected, that makes the `brief` verb work as expected.

So, unless we can come up with another way to track the number of visits and description of each location, we'll have to either remove from the library the `brief` and `verbose` commands, or renounce to the `visited` and `described` attributes — personally, I see more value in the latter, so if I had to choose I'd definitely give up `brief`. These two attributes are too useful to renounce.

Before removing those two verbs, do you have any idea of how the situation could be fixed?

Frankly, I don't see many solutions, as tracking location's visits somewhere else other than the location itself doesn't seem feasabile. At least, I can't think of any solution right now.

**Comment by AnssiR66** [comment]
We might wait first what Thomas has to  say about the issue. If he agrees to change the behavior of VISITS so that it doesn't reset when a location attribute changes, we don't have to anything. If this is not the case, we can probably remove brief/verbose if no other solution is found. I'm thinking of an alternative way presently and will let you know if I come up with anything... probably most we can do is instruct the player who really wants it implemented, to make some kind of subclass of location and then use Description Checks (like in the dark_location class presently).

-Anssi




________________________________

**Comment by tajmone** [comment]
@AnssiR66, you should decide what to do with the `brief` and `verbose` commands, i.e. if dropping them altogether from the library. Chances are that these won't work even in the future, because from the discussion with Thomas it's clear that it's an intended feature that Alan should ignore the value of `VISITS` when a location attributes change — which makes sense in most contexts.

Both the _StdLib Manual_ and the _Cookbook_ should be amended in various places where  `brief` and `verbose` are mentioned. After all, one of the main purposes of the upcoming Lib 2.2 release is to update all the documentation to match the current state of the Library, and find/resolve all pending bugs in both code and documentation.

**Comment by AnssiR66** [comment]
Yes, let's get rid of brief and verbose. I think 'brief' is very archaic anyway.
