### ISSUE TITLE
Documents License Terms?

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#4]
@AnssiR66, do the documentation files in this project fall under the same license of the project (Artistic License 2.0)?

Also, what are the license terms for _The Alan Cookbook_?

I'm asking you because I was thnking of converting some of the documents to HTML at some point in the future — ie, the _ALAN Library2.1 manual_, _QuickStart_ and _QuickRef_ — and possibly also the _Cookbook_.

I had in mind to use pandoc, a universal document conversion tool which I often use for documentation project, and use pandoc markdown flavor for the base documents, which could then be converted to HTML5 and various other formats (including docx/PDF, ePub, etc.). Furthermore, by using a macros system, I could use an external highlighter tool to syntax highlight the Alan source code in the documents, which would add an extra touch of elegance.

This would make maintainance and collaboration easier on the docs because of markdown being a text format, and the HTML5 output could also be used here as online documentation via GitHub pages website (by storing the generated static HTML files in the `docs` folder). For Windows, I could also create an executable eBook to gather all the HTML documents in a single binary file, pretty much like an off-line website browser.

Here is an example of a documentation project which I created using this system:

- https://github.com/tajmone/polygen-docs (source docs)
- https://github.com/tajmone/polygen-docs/blob/master/polygen-spec_EN.html (live preview)

**Comment by AnssiR66** [comment]
Hi Tristano!
Yes, all library files, including the library, are under the same license. The Cookbook does not mention any specific license but it could very well use the same license for clarity. I will add that mention in the future versions.

Your plans regarding converting the files sound good! Let me know how it goes forward.

-Anssi




________________________________

**Comment by tajmone** [comment]
Thanks! I'll keep you updated on this.

I've started working on the Alan syntax definition for the highlighter tool, and will create a version for pure Alan code and another that includes also the StdLib, so we can get the best highlighting experience for both codes in the docs.

When some draft is available I'll let you know.
