### ISSUE TITLE
Optimizing Restricted Actions Initialization

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#6]
I was thinking that `lib_definitions.i` could be optimized in some places.

The `check_restriction` EVENT uses a `=` operator to check the restriction level, and then sets _every_ verb restriction attribute accordingly, so it's working like a "select" statement with lots of redundancy. But it seems to me that restriction levels are "layered" in nature, ie: each level adds further restrictions to the previous ones, so the whole EVENT could be slimmed down by using a `>=` operator instead, and for each level set only those attributes whose restriction is introduced by that particular level.

```alan
EVENT check_restriction

IF restricted_level OF my_game >= 0    -- all verbs work normally
  THEN
  -- [...] set all verb restriction attributes to TRUE
  --       (probably this whole block could be left out altogether)
ENDIF.

IF restricted_level OF my_game >= 1  -- communication verbs are restricted
  THEN
  -- [...] only set attributes of communication verbs to NOT
ENDIF.

IF restricted_level OF my_game >= 2  -- all action verbs, including communication verbs,
                                     -- are restricted. Verbs like 'examine', 'look', , 'inventory, 'think'
                                     -- 'wait' and sensory verbs as well as all out-of-game verbs work
  THEN
  -- [...] only set attributes of required verbs to NOT 
  --       (excluding those already covered by restricted_level >= 1 )
ENDIF.

```

... and so on. Here for any given restriction level, all the relevant IF blocks are executed in sequence.

Also, I think that the first block (ie: `my_game >= 0`) could be left out entirely as it sets all attributes to TRUE, which should be the default value of attributes anyway — as a matter of fact, currently the IF block for `my_game = 1` only sets the attributes which need to be NOT:

```alan
ELSIF restricted_level OF my_game = 1  -- communication verbs are restricted
  THEN

  MAKE my_game NOT answer.
  MAKE my_game NOT ask.
  MAKE my_game NOT ask_for.
  MAKE my_game NOT 'say'.
  MAKE my_game NOT say_to.
  MAKE my_game NOT shout.
  MAKE my_game NOT sing.
  MAKE my_game NOT tell.

ELSIF restricted_level OF my_game = 2 
```

... which seems to confirm that there is no need to explicitly set boolean attributes to TRUE.

This would reduce the source file by a considerable number of lines, and make it easier to study — and, possibly, also easier to maintain.

**Comment by tajmone** [comment]
After looking closer at it, I realized that this is an EVENT running on every turn, so I guess that it's intended to detected changes in the restriction level during game play, so probably the first block should always set to boolean true all attributes. But the rest of the considerations still apply.

But then, since this EVENT is executed on every turn, wouldn't it be better to have an extra attribute storing the latest used restricted level (eg, `restricted_level_old`) so that the code is only executed if changes are detected in the value of `restricted_level`?

```alan
IF restricted_level OF my_game <> restricted_level_old OF my_game
    THEN
    [...] -- (... reset attributes accordingly)
    -- finally, set 'restricted_level_old' to the new value of 'restricted_level'
```

Being a rather long block, optimizing the code to prevent redundant attributes changes with same values as in previous turn could have a positive impact on gameplay. Currently, it resets all attributes to the values of the current restriction level at every turn, even if the level didn't change. This could definitely be optimized.

**Comment by AnssiR66** [comment]
Hi Tristano!


Sorry for the delay in replying. I am in the Philippines this month and the network signal here in the countryside is weak. I definitely agree that there could be an extra attribute preventing the unnecessary every-turn checks, but I will address these issues only when I get back from the trip at the end of this month. So, I will be writing in more detail in very early August. Thanks for noticing the issue,  and please keep writing about any other issues you might find!

Thanks,

Best regards

Anssi

________________________________

**Comment by tajmone** [comment]
I did some test with this locally, and ultimately I think that what we can achieve here is an optimization in performance more than in code size.

From what I gather, the library resets all these attributes at every time, while having a temporary variable to store the last value that triggered a status change for restricted actions would reduce the number of operations when it didn't change.

There might be some space for code size optimization too, but probably limited.

**Comment by AnssiR66** [comment]
OK, sounds good! Please go ahead and let me know if you found any problems with that approach, we'll go from there...
