### ISSUE TITLE
Tutorials Toolchain for Extras Folder

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#66]
Ciao Anssi,

regarding what you said in Issue #65:

> Good that you are working on the tutorial; we can include that in the library manual once it's ready. As you have implemented the new code for the clothing class, I think it's wise if you coin up the manual for it first and then we can integrate it to the full library manual consequently.

I've managed to setup an updated Clothing Guide draft for the new system, that comes with sample adventures. But I've also set up an automated toolchain to allow easy inclusion of selected parts of the Alan source into the tutorial document, as well as game transcripts.

This toolchain actually compiles the adventures and run the command scripts at each document conversion from HTML, which means that even if library changes were to modify the actual output in the adventure, the documents will always mirror the current state of the library at the time of their conversion.

Also, this system allows to easily buil "incremental tutorials" from a single Alan source, by hiding selected parts of the code (e.g. a verb inside an instance) as if it was added later on. And if you edit the Alan source adventures, and line number position change in the code, this doesn't affect the output document.

So it's a good way to maintain tutorials without having to worry about future changes in the library.

Have a look at it (still in the clothing dev branch).

## A Cleaner "Extras" Folder

Now all the source assets are inside the `extras_src/` folder, and only the output HTML docs and Alan examples (cleaned up) end up in `extras/`, because we want to keep the end-users folder free from clutter.

It's also possible to use `.gitattributes` to tell GitHub to exclude certain developer files and folder from the Zip files that users can download from GitHub web pages (download button and releases). This would allow users who don't use Git, and prefer to download the Library via the download button on GitHub, to get just the essential files — no dev folders, no Git config files, and anything else that is not important for the library usage.

## Alan CookBook Thoughts

I was thinking that we should consider using this system also for the _Alan Cookbook_, instead of giving just a PDF file. This way we could provide also a nicely formatted HTML version + example sources — and, of course, we can also convert from AsciiDoc to PDF, as an added bonus.

This would be easier to maintain than using an ODT/Word file, which can't be easily version controlled; plus we would always be able to provide up-to-date transcripts from the current library, by running the examples lives through ARun and capturing the output.

I've noticed that quite a few examples in the CookBook no longer work with the current library. Manually updating it is going to be hard work on the long run, automation is a better path IMO. Also, AsciiDoc allows version control, which opens the doors to user contribution, and also provides separates between contents and styling, allowing to "print" the same source document in any style/template one wishes.

What do you think?

**Comment by AnssiR66** [comment]
Hi Tristano!
What you suggest sounds good to me, regarding both the clothing update to the library/manual and the CookBook update. The toolchain idea sounds cool in its flexibility.
I took a look in the dev_clothing branch and at the new clothing instructions you have written, and it looks very good and clear. Again, thank you for the huge work!

Yes, the cookbook code needs some updating. I'll need to take a look, and update not only the clothing bits but probably quite a number of entries here and there.

So... what is the next concrete step in the update process, if we think of the clothing class? How can I help there?

And, I guess, as far the cookbook is concerned, I would update the code there first, before we apply it to the new platform?

-Anssi
________________________________

**Comment by tajmone** [comment]
> So... what is the next concrete step in the update process, if we think of the clothing class? How can I help there?

Right now it's important to decide about the versioning scheme strategy, [as proposed in #65](https://github.com/AnssiR66/AlanStdLib/issues/65#issuecomment-480496482), because it will determine if the current clothing dev branch is going to be squahsed directly in `master` or in a `dev-2.2` dev branch first — meaning, in the former case I'd need to completely polish everything before squashing, while in the latter I'd only need to ensure that the library code part is taken care of, for there'd be space for more commits (and dev branches) before the final merge.

If (as proposed) we create a `dev-2.2` dev branch, as soon as I can squash the current changes we'd be free to start further branching, so each one of us could work on specific aspects independently without worrying about merge conflicts.

> And, I guess, as far the cookbook is concerned, I would update the code there first, before we apply it to the new platform?

I actually suggest to start by converting the CookBook (as it is) to the new system (ie. splitting into independent recipies, each with it's document, source example and test scripts). The documentation toolchain would automatically reveal any code that is no longer working (either via compiler errors or by looking at the transcripts).

You could then start to work on each recipe individually in the new system, which should be much faster to edit and edit. One of the advantages of this toolchain is that you can also use command scripts just to test that the examples are working as expected, even if the transcript is not shown in the final HTML documents.

The CookBook is currently only available in PDF, I did manually copy and paste some examples to Alan sources for my own tests, but if you could hand me over the original document (ODT/Word?) I could quickly convert it to AsciiDoc via some scripts, and split it into individual recipies, code examples and scripts. Then you could start editing it in a dev branch, with everything in place.

This approach should speed up the whole process and save some time, and allow us to work on separate branches and then merge them together.

**Comment by AnssiR66** [comment]
Hi Tristano,
sorry for a late reply again. What you suggest about the individual dev branches sounds good. I attach here the Cookbook v2, which I only found as a .txt and a .pdf version for now - is that ok?
I'm  on a train and can only write in short  - we'll be in touch!
Anssi

**Comment by tajmone** [comment]
> sorry for a late reply again.

nothing to aplogize, I'm slowing down too, a bit for the work overload, and a bit because I'm trying to enjoy the few days of spring we get.

> What you suggest about the individual dev branches sounds good. 

Good to know.

> I attach here the Cookbook v2, which I only found as a .txt and a .pdf version for now - is that ok?

If they are the same as those distributed with the Library, then I have them too. If you can't find the original Word/ODT then they'll have to do. A bit of extra work, but nothing huge. If you happen to find the original, please post it via email, if not I'll just start to work with the txt version, and then compare it to the PDF (just to make sure).
