### ISSUE TITLE
Artistic License 2.1?

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#72]
I noticed that the `COPYING.txt` license file mentions Artistic License 2.1:

```
The Alan Standard Library v2.1 is distributed under the Artistic License 2.1 for which the
full text follows. The intent of this licensing is that the Copyright Holder retains some
control over the development of the library, while still keeping it available as open source
free of charge.

In practical terms this means that the licensing is chosen so that it should be possible to
- freely distribute games produced using the library, including for profit
- modify the source code of the library for inclusion in games, including commercial games 
- redistribute compiled and/or source versions of the original library
- redistribute compiled and/or source of modified Versions of the library provided they are
  done so under a compatible license with appropriate attribution


Artistic License 2.1
====================
```

I think this an error due to search and replace operations when you bumped from StdLib 2.0 to 2.1, because there doesn't seem to exist a version 2.1 of the Artistic License:

- https://opensource.org/licenses/Artistic-2.0
- https://choosealicense.com/appendix/
- https://choosealicense.com/licenses/artistic-2.0/

This needs to be fixed ASAP!

**Comment by AnssiR66** [comment]
A good catch! I will change this right away.

________________________________

**Comment by tajmone** [comment]
Let me do it because I've already started moving the files in StdLib locally, so I don't have to integrate it again.

**Comment by AnssiR66** [comment]
Ouch! I did it already, but see what you can do and fix it accordingly if needed...

________________________________

**Comment by tajmone** [comment]
Fixed:

https://github.com/AnssiR66/AlanStdLib/blob/dev-2.2.0-repo-structure/StdLib/COPYING

> Ouch! I did it already, but see what you can do and fix it accordingly if needed...

No big deal. I'll just overwrite it.
