### ISSUE TITLE
StdLib Manual: Styling Player-Input & Parser Responses

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#75]
Ciao @AnssiR66,

I'm testing a new inline style for the StdLib Manual, for when in the flow of text there's either a player input or a parser response. I wanted to color it the same way as game transcripts are styles.

Here are two screenshot and direct links (live HTML) to a couple of examples:

- [Example 1](http://htmlpreview.github.io/?https://github.com/tajmone/AlanStdLib/blob/wk-docs/extras/manual/StdLibMan.html#xxx1) 

![Example 1](https://i.ibb.co/KGx0PKH/player-input1.png)

And below, there's also a parser response example:

- [Example 2](http://htmlpreview.github.io/?https://github.com/tajmone/AlanStdLib/blob/wk-docs/extras/manual/StdLibMan.html#xxx2) 

![Example 2](https://i.ibb.co/HnhhQz8/player-input2.png)

You'll notice that I've remove the quotation marks from the parser response, because now the style colors make them redundant.

Before going ahead with this, and applying these styles to all occurence of inline player input & parser responses, I wanted confirmation from you that you like the style and I can carry on.

Currently these styles are in a separate test branch in my fork, so if you don't like them I can just drop the commit.

Please, not that I can't go ahead with the work until you confirm/disconfirm this.

PS: Sorry for not having dedeicate more time to the StdLib lately, but I've been really busy and stuck. Hopefully now I can go ahead full regime.

**Comment by AnssiR66** [comment]
Hi Tristano, and sorry also for not responding for some time. For me, what you suggest is perfectly alright. We can do like that.
Best,
Anssi

________________________________
