### ISSUE TITLE
Add EditorConfig Settings

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#79]
Take the [`.editorconfig` file][.editorconfig] from the [ALAN Repository Template] and add it to the project root folder.

This will add application agnostic setting for Alan related files (`*.alan`, `*.i`, `*.a3sol`, `*.a3log`) via [EditorConfig], ensuring consistent code styling across different editors and IDEs, and [improve Alan sources visualization on GitHub].

[.editorconfig]: https://raw.githubusercontent.com/alan-if/alan-repository-template/master/.editorconfig "View raw source file"
[ALAN Repository Template]: https://github.com/alan-if/alan-repository-template "Visit the ALAN Repository Template project on GitHub"
[EditorConfig]: https://editorconfig.org/ "Visit the EditorConfig project website"
[improve Alan sources visualization on GitHub]: https://github.com/editorconfig/editorconfig.github.com/pull/48

**Comment by tajmone** [comment]
@AnssiR66 , forgive me ... I've pushed this change directly to master branch, forgot to make a Pull Request for it (I was adding the same file to many Alan repositories at once, and it came just automatic).

Hopefully, it's not a big deal, for it just adds an extra settings file which adds editors and IDEs settings for Alan sources and files, and no files were changed except a line in `.gitattributes`.

I hope it didn't interfere with some branches you were working on. If it did, we can unroll the commit. _Mea culpa!_ I forgot ...

**Comment by AnssiR66** [comment]
Hi Tristano! I don't think it's any problem. 🙂 It's good it's there now.
I don't think it interfered with anything...
Best,
Anssi

________________________________

**Comment by tajmone** [comment]
# Add Again EditorConfig Settings and Improve Them

For some reason the `.editorconfig` settings file is no longer found in any branch. No idea why, but it seems I had only pushed them to my fork actually (need to check whether it's still in synch with the upsteam)..

In any case, after the release v2.2 is out, we definitely need to add some good EditorConfig settings, as well as to enforce code styles validation on commits and PRs via Travis CI (or GH Actions) using EClint.
