### ISSUE TITLE
Optimizing the Banner: Does it have to be a DEFINITION_BLOCK?

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#8]
While working on the StdLib code to translate it, I'm getting more acquainted with its internals, and gaining a bit more confidence regarding its structure.

I was trying to figure out: why the `banner` is an instance of `DEFINITION_BLOCK`?

From what I can see, the `banner` doesn't need any of the `DEFINITION_BLOCK` attributes for itself, since it only refers to the attributes of `my_game` instance — ie, the title, subtitle, author, etc.

The potential problem with this is that of memory consumption: the `DEFINITION_BLOCK` class has a _HUGE_ amount of attributes. Having two instances of this class duplicates both the memory consumption as well as the execution time.

I checked with the Alan debugger, and I can see that the instance of `banner` has a really long list of attributes, and persists in memory during game play (along with its twin `my_game` instance).

Wouldn't it be possible (and better) to avoid making `banner` an instance of `DEFINITION_BLOCK` to contain the `DEFINITION` to be shown at start up? A `DEFINITION_BLOCK` is a location hidden from the player, right? Wouldn't the banner work if it was just an instance of the base `LOCATION` class?

If I understood correctly, the goal is to provide a clean statement to the end user: `DESCRIBE banner.`.

I'm sure there was some reason why you came up with this solution, but I think that by using some workaround it could be possible to find a way to avoid having two  `DEFINITION_BLOCK` instances in the game. After all, the `banner` always prints out the attributes of `my_game`, not its own attributes, so it could just be a simple `LOCATION` — after all, the only purpose of the banner is for it to be printed out via the `DESCRIBE banner.` statment that follows the `Start at` statement, right?

Or am I missing something-out here?

**Comment by tajmone** [comment]
### A Small Test

I've just tried to change `lib_definitions.i`, making the `banner` an instance of `LOCATION` instad of `DEFINITION_BLOCK`__

```alan
-- THE banner ISA DEFINITION_BLOCK
THE banner ISA LOCATION

    DESCRIPTION
    -- [... etc. ...]
```

... and compiled an adventure to test it.

The adventure seems to work just fine (the banner is displayed as expected at startup, and game play seems as usual).

With the debugger, now the `banner` instance is really short:

```
adbg> instances 9
instances 9
The [9] banner ("banner") Isa location[2]
    Attributes:
        visits[1] = 0
        plurale[2] = 0
        femminile[3] = 0
        nested[45] = 18638576
        lit[46] = 1
        visited[47] = 0
        described[48] = 0
adbg>
```

... while before it was many terminal-pages long (hundreds of attributes).

### Size Differences

Also, the size of the compiled adventure is smaller (20Kb less) — probably that would be the total bloat regardless of the adventure lenght (20Kb is reasonably the probable size of a `DEFINITION_BLOCK` instance, with all its data structures and strings). The adventure I used to test it is rather small (350Kb with untweaked lib, 320Kb with `LOCATION` tweak), and the library most surely occupies most of the memory space since it's bigger than the game code.

### Standing By for Your Advise

Of course, I could be missing out something important here, so I'll just wait for your reply on this. Also, being a very small change, it might not be even worth creating a pull-request for it.

Let me know!

**Comment by AnssiR66** [comment]
Great thinking!
I don't remember why I originally declared the banner to be a definition_block, it is obvious that it can be just a normal location (or even an object). I'll change that myself, you won't have to make a commit about it.

Cheers,

Anssi



________________________________

**Comment by tajmone** [comment]
I guess that having ported the library from the previous Alan version to Alan 3 involved lots of adaptation work and — being the library so huge in size — it's more than normal to get entangled in all the changes and overlook details like this.

For me it's easier because I'm taking a "fresh" approach to the Library code, and am seeing it for the first time and learning it inside out. But when I work on my Italian adapted code I also end up being too involved and entangled in it, and overlook some things which I give for granted.

As a general rule, I tend to use consistent code formatting as a means to allow using RegExs to quickly bring up all occurrences of certain code patterns, to either keep an eye on them or to quickly apply substitutions on the whole library. This is the reason why I sometimes make pull request for code reformatting, removing tabs and introducing uniform whitespaces (and, sometimes, even extra spaces). Also my editor (Sublime Text) relies on whitespace and indentation for code-folding and contextual selection, which helps me a lot when editing the library sources.

This system allows me to produce a find-results page showing all occurrences of a given code pattern, presented with a couple of preceding and following lines, and line numbers, which is a very handy way to check how the library is handling any code pattern, and if I've overlooked something during work.

The more I get to know the StdLib, the more I'm impressed by your work! It's a really solid library, well thought and designed, and I'm learning a lot about IF authoring in general by studying and adapting it.

Also, I noticed that the Italian IF community is getting quite excited about the upcoming Italian Alan Library translation, so I really hope that it will be ready by Christmas. Currently I've translated more than half the verbs, but there is a lot of work to be done for the verb response messages, as these need to be adapted to the Italian language and require a different approach. So my guess is that the translation might be ready in September, but a few more months will be required to polish up things and optimize it.

**Comment by AnssiR66** [comment]
Thanks for your comments about the StdLib, I am glad if you find it solid and useful. Yes, I have spent several years on it, adding things little by little. I think at this point it is as extensive as it needs to be and any new features might be achieved through separate extensions. You've also done a great job translating it to Italian - I know it's a challenge because of the article issues etc.  - and I'm happy to hear you're rather close to completing it. It's also sounds great that the Italian IF community shows interest in it, more widely speaking. :)


-Anssi



________________________________
