### ISSUE TITLE
Broken Sentences in StdLib Man

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#80]
@AnssiR66, in this Issue thread I'll be calling your attention to problematic sentences in the _StdLib Manual_ which need to be fixed.

- [_StdLib Manual_ (dev) — Live Preview][ManLive]

[ManLive]: http://htmlpreview.github.io/?https://github.com/AnssiR66/AlanStdLib/blob/dev-2.2.0-docs/extras/manual/StdLibMan.html

**Comment by tajmone** [comment]
# Problem in §2.1: Misunderstood Prompt?

In [_StdLib Manual_ §2.1][§2.1] it says:

> This code compiles successfully and doesn’t use the library at all. When you try to play this game, you will find yourself at a location called 'Meadow' but you won’t be able to do anything, __not even prompt will be understood__. You should go on implementing everything by yourself.

It's not clear what you mean by  __"not even prompt will be understood"__ — beside the missing article ("the prompt"), the sentence meaning is problematic.

The _command line prompt_ is a built-in feature of the ALAN user interface, where players can type their commands. It's always there, regardless of the adventure sources code; and it can't be understood or misunderstood, for it's just an interface between the player the built-in commands parser.

What are you trying to say here? My guess is that you meant that no player commands will be understood, for none were defined in the example adventure.

Any suggestions on how to fix that sentence?

[§2.1]: http://htmlpreview.github.io/?https://github.com/AnssiR66/AlanStdLib/blob/dev-2.2.0-docs/extras/manual/StdLibMan.html#_how_to_import_the_standard_library_into_an_alan_game

**Comment by AnssiR66** [comment]
Yes, there are some words missing there. Obviously it means, "Nothing you type at the prompt will be understood."
