### ISSUE TITLE
Improved Modularization of StdLib

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#87]
From my late experience with the Italian port of the StdLib, I would strongly suggest a few changes to the library modules, i.e. moving around some code dealing with specific aspects to independent source modules, or in a more appropriate one among the already existing ones.

I suggest:

1. Renaming `lib_messages.i` &rarr; `lib_messages_runtime.i`.
2. Creating `lib_messages_library.i` and moving therein all the response string attributes, currently stored in `lib_definitions.i`
3. Creating `lib_verbs_restrictions.i` and moving therein all the code dealing with verb restrictions, currently stored in `lib_definitions.i`

Since end users only need to include `library.i` in their adventures, which takes care of all the other modules, an increased number of library files shouldn't bother them at all.

On the other hand, in terms of code maintenance, for us, and for end users wanting to tweak and customize the library sources, a more modular approach is much neater to handle and simpler to study — the `lib_definitions.i` module is too big to be practical to handle.

The new library structure would look much more intuitive in terms of where to find what:

- `library.i` — main file, importing all others:
    + `lib_classes.i` (_as usual_)
    + `lib_definitions.i` — core definitions, banner, etc.
    + `lib_locations.i` (_as usual_)
    + `lib_messages_library.i` — Library messages definitions.
    + `lib_messages_runtime.i` — Run-Time messages.
    + `lib_verbs.i` — verbs definitions.
    + `lib_verbs_restrictions.i` — verbs restrictions code.

(See also #25, on the rationale for doing this in StdLib Italian.)

**Comment by AnssiR66** [comment]
ok, sounds good. the new structure sounds clearer, so we can go for it
