### ISSUE TITLE
Tweaked Examine Verb with Readable Objects

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#9]
- [x] Tweak Library code and implement feature.
- [x] Create test for it:
    - [`tests/house/readable-objects.a3sol`][a3sol]
    - [`tests/house/readable-objects.a3log`][a3log]
- [ ] Mention it in StdLib Manual

[a3sol]: https://github.com/AnssiR66/AlanStdLib/blob/dev-2.2.0/tests/house/readable-objects.a3sol "View solution script"
[a3log]: https://github.com/AnssiR66/AlanStdLib/blob/dev-2.2.0/tests/house/readable-objects.a3log "View transcript log"

-------------------------------------------------------------------------------

I wanted to share with you some tweaks I've made in the Italian library for the `examine` verb — see __[commit afe002c16]__.

[commit afe002c16]: https://github.com/tajmone/Alan3-Italian/commit/afe002c16b42bf997e42d916779322151486480b

Here the description of the tweaks from the [CHANGELOG]:

[CHANGELOG]: https://github.com/tajmone/Alan3-Italian/blob/master/alanlib_ita/CHANGELOG.md#changed-behaviour-of-examine

> ## Changed Behaviour of `examine`
>
> In the original library, when the verb `examine` was used with readable objects it behaved just like `read`.
>
> I wanted to change this because in some circumstances you'd like an object to both examinable and readable. For example, an ancient book: you'd like provide to the player a detailed description of the book when he examines it ("_It's an old leather bound book covered in esoteric symbols and secured by a golden seal._"), which increases the curiosity towards its contents, which can then be accessed by reading it.
>
> At other times, you might just want both `examine` and `read` to act the same. For example, a small note, a sticky-post, for which the description is not relevant to the game atmosphere.
>
> So, I've opted for a solution that allows to preserve the old behavior and also introduce the possibility of examining a readable object.
>
> Now the `examine` verb was changed so that when obj is a readable object:
>
> - If the object's `ex` string is not empty, _examine it_ and print the contents `ex`
> - If its `ex` is empty, and it's a readable object with a non empty `text`, then _read it_ instead.
> - If both `ex` and `text` of a readable obj are null strings, just print the usual "_You notice nothing unusual about (the obj)._"
>
> With the new system, to old library behavior is preserved for readable objects which have text only in their `text` attribute. If the author also adds text to `ex`, then it means that he wants the object to be separately examined and read, and the new behavior prevails.

Here is the [link to the tweaked code].

[link to the tweaked code]: https://github.com/tajmone/Alan3-Italian/blob/afe002c16/alanlib_ita/lib_verbi.i#L926

Basically, I've just changed the `DOES` part a bit (unfortunately, the code has been already heavily _Italianized_, but the changes should be self-evident):

```alan
    DOES
      IF ex OF obj <> ""
        THEN SAY ex OF obj.
      ELSIF obj IS leggibile AND testo OF obj <> ""
      --+-----------------------------------------------------------------------
      --| Se la stringa 'ex' dell'oggetto è vuota, e si tratta di un leggibile
      --| contenente del 'testo', allora ESAMINA si comporterà come LEGGI:
      --+-----------------------------------------------------------------------
        THEN "Leggi" SAY THE obj. "."
          IF obj IS NOT plurale
            THEN "Dice"
            ELSE "Dicono"
          END IF.
          """$$" SAY testo OF obj. "$$""."
      ELSIF obj = hero
     -- THEN "You notice nothing unusual about yourself."
        THEN "Non noti niente di insolito in te stesso."
        ELSE "Esamini" SAY THE obj. ", ma non noti niente di speciale."
     -- ELSE "You notice nothing unusual about" SAY THE obj. "."
      END IF.
  END VERB.
```

Maybe you could consider adding this tweak to the next version of the StdLib — it doesn't prevent the old behaviour but adds the choice of creating some readable objects that can also be examined.

We could ask on the Alan group what other users think about it.

**Comment by tajmone** [comment]
@AnssiR66, this proposal has been pending a decision for quite a long time.

I would really like to see it implemented in `v2.2.0` — it's a small change, already tested in the Italian library, it's totally backward compatible but it allows authors to implement readable objects that are also examinable.

I think it's a good enhancement, since this is how most IF libraries handle readable objects. Just imagine a scenario like this one:

> #### The Wizard Den
> 
> There's a strange looking book ling on the altar.
> 
> &gt; _x book_
> 
> It seems to be an ancient manuscript, bound in a black leather jacket with ominous magic symbols engraved all over its cover.
> 
> &gt; _read it_
> 
> Page after page, the book narrates the ancient origins of magic, and then goes on revealing spells and formulas to dominate the elements of nature...

being able to examine the book is an important aspect of the game play, for it sets the mood and atmosphere, creating anticipation and strengthening the action of reading it.

**Comment by AnssiR66** [comment]
Yes, we can do this. How do we go about it, shall I change it?

**Comment by tajmone** [comment]
> Yes, we can do this. How do we go about it, shall I change it?

If it's OK with you I'll do it, so I can immediately rebase the docs branch, and partly because I've already done it before and will create the tests for it too.

**Comment by AnssiR66** [comment]
Yes, sure!
