### ISSUE TITLE
Honoring 'ex' Attribute when Examining Scenery

### ISSUE THREAD

**Issue by tajmone** [AnssiR66/AlanStdLib#99]
@AnssiR66, I think that the `examine` VERB should honor an `ex` attribute of a `scenery` object, if present.

Even though scenery objects are not important for the game, and are just scenic props, the author should still be allowed to provide a custom description for when these objects are examined, because props can deliver mood to the environment, provide clues of things to come, and even move the story forward, if well crafted.

I think that the `examine` verb should be tweaked so that it will show the "The [obj] is not important..." message for `scenery` objects only if their `ex` attribute is an empty string, and honor the custom description otherwise.

**Comment by AnssiR66** [comment]
Yes, that's reasonable. We can make that change for the scenery objects.

**Comment by tajmone** [comment]
@AnssiR66, I've fixed the behavior of `examine` for `scenery` objects that have an `ex` string defined. The results are good, and they work well with the similar changes to `readable` objects (#9), and now it's possible to quickly create scenery objects which are also readable.

Check out the test transcript to see how it plays out neatly:

- [`scenery-objects.a3log`][scenery-objects.a3log]




[scenery-objects.a3log]: https://github.com/AnssiR66/AlanStdLib/blob/dev-2.2.0/tests/house/scenery-objects.a3log

**Comment by AnssiR66** [comment]
👍 Works great!
